spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}
    debug: true
  admin:
    firstname: ${ADMIN_FIRSTNAME}
    lastname: ${ADMIN_LASTNAME}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_EMAIL_USERNAME}
    password: ${SENDER_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  app:
    jwtSecret: ${SPRING_APP_JWT_SECRET}
    jwtExpirationMs: ${SPRING_APP_JWT_EXPIRATION_MS}
    jwtRefreshExpirationMs: ${SPRING_APP_JWT_REFRESH_EXPIRATION_MS}

logging:
  level:
    org:
      springframework:
        security: TRACE
        security.web.FilterChainProxy: TRACE
        security.authentication: TRACE
        web: DEBUG
        mail: DEBUG
      eclipse:
        angus:
          mail: DEBUG
      jakarta:
        mail: DEBUG
      orm:
        jdbc:
          bind: TRACE

    com:
      chillies:
        hearttohome: DEBUG
        hearttohome.security: TRACE
        hearttohome.security.jwt: TRACE

    io:
      jsonwebtoken: DEBUG
frontend:
  url: ${FRONTEND_URL}
stripe:
  key:
    secret: ${STRIPE_KEY_SECRET}
  webhook:
    key: ${STRIPE_WEBHOOK_SECRET}
sender:
  email: ${SENDER_EMAIL_USERNAME}
